### ISSUE TITLE
Missing a=ice-options attribute in answer sdp

### ISSUE THREAD

**Issue by syerrapragada** [otalk/rtcpeerconnection-shim#155]
`createAnswer` doesn't set `a=ice-options:trickle` in the sdp.

**Comment by fippo** [comment]
right, see http://rtcweb-wg.github.io/jsep/#rfc.section.5.3.1
```
 except that the "a=ice-options" line, with the "trickle" option as specified in
[I-D.ietf-ice-trickle], Section 4, is only included if such an option was 
present in the offer.
```
Now I wonder if the list of options is declaritive or a subset of the offer...

**Comment by syerrapragada** [comment]
@fippo
For this issue is following a potential solution?

Adding following check at https://github.com/otalk/rtcpeerconnection-shim/blob/master/rtcpeerconnection.js#L1324
```
if(pc._canTrickleIceCandidates) {
  sdp += 'a=ice-options:trickle\r\n';
}
```

**Comment by fippo** [comment]
it looks like ice-options is declarative, see discussion in https://mozilla.logbot.info/media/20180905#c15270769

i'll have a patch shortly.

**Comment by fippo** [comment]
cherry-picked into the 1.2.14 patch release
