### ISSUE TITLE
Asymmetic media negotiation fails

### ISSUE THREAD

**Issue by syerrapragada** [otalk/rtcpeerconnection-shim#162]
```
     console.log('pc1 adds an video track');
      const stream1 = await navigator.mediaDevices.getUserMedia({video: true, fake: true});
      const [localVideoTrack] = stream1.getVideoTracks();
      pc1.addTrack(localVideoTrack, stream1);

      console.log('pc2 adds an audio track');
      const stream2 = await navigator.mediaDevices.getUserMedia({audio: true, fake: true});
      const [localAudioTrack1] = stream2.getAudioTracks();
      pc2.addTrack(localAudioTrack1, stream2);

      console.log('pc1 and pc2 negotiate');
      offer = await pc1.createOffer();
      await Promise.all([pc1.setLocalDescription(offer), pc2.setRemoteDescription(offer)]);
      answer = await pc2.createAnswer();
      await Promise.all([await pc2.setLocalDescription(answer), await pc1.setRemoteDescription(answer)]);
```

Above example fails to negotiate.

**Comment by fippo** [comment]
http://jsfiddle.net/on9camy8/2/
throws an InvalidAccessError (I think from sender.send) and says "unable to get property sdp of undefined or null reference. The answer seems to have kind=audio with h264 which is... weird.

**Comment by syerrapragada** [comment]
`unable to get property sdp of undefined or null reference` is a different issue. It happens due to `_gather` being called before `_localDescription` is set in `setLocalDescription`

**Comment by syerrapragada** [comment]
kind=audio with h264 could be due to that `setRemoteDescription` doesn't check for the kind of media when iterating through transceivers? I am still going thru the code to understand how things work

**Comment by fippo** [comment]
This seems to pick the wrong internal transceiver yes. pc.addTrack creates an internal transceiver and then that transceiver is used in setRemoteDescription even though the `kind` does not match.

If you move the addTrack call from the fiddle *after* setRemoteDescription but before createAnswer things work.

Pretty nasty bug, I wonder why this did not become an issue earlier...

**Comment by fippo** [comment]
master behaves a bit different but still wrong. This is a simpler test:
```
  it.only('does not do the wrong thing', (done) => {
    const sdp = SDP_BOILERPLATE + MINIMAL_AUDIO_MLINE;
    const pc = new RTCPeerConnection();
    return navigator.mediaDevices.getUserMedia({video: true})
      .then((stream => pc.addTrack(stream.getTracks()[0], stream)))
      .then(() => pc.setRemoteDescription({type: 'offer', sdp}))
      .then(() => {
        console.log(pc._transceivers);
      })
      .then(() => pc.createAnswer())
      .then((answer) => {
        console.log(answer.sdp);
      });
  });
```
pc._transceivers should have length two and the returned answer should not do video.

**Comment by fippo** [comment]
the issue is quite tricky as a lot of code in createOffer/createAnswer assumes that the order of m-lines is the order in which _transceivers is sorted. The "proper" solution is probably to add a sdpMLineIndex field to the transceiver structure and use that consistently.
Here is another example where this fails:
```
    it.only('keeps the order from the remote offer', (done) => {
      const sdp = SDP_BOILERPLATE + MINIMAL_AUDIO_MLINE +
        'm=video 9 UDP/TLS/RTP/SAVPF 102\r\n' +
        'c=IN IP4 0.0.0.0\r\n' +
        'a=rtcp:9 IN IP4 0.0.0.0\r\n' +
        'a=ice-ufrag:' + ICEUFRAG + '\r\n' +
        'a=ice-pwd:' + ICEPWD + '\r\n' +
        'a=fingerprint:sha-256 ' + FINGERPRINT_SHA256 + '\r\n' +
        'a=setup:actpass\r\n' +
        'a=mid:video1\r\n' +
        'a=sendrecv\r\n' +
        'a=rtcp-mux\r\n' +
        'a=rtcp-rsize\r\n' +
        'a=rtpmap:102 vp8/90000\r\n';
      return navigator.mediaDevices.getUserMedia({audio: true, video: true})
        .then((stream) => {
          pc.addTrack(stream.getVideoTracks()[0], stream);
          pc.addTrack(stream.getAudioTracks()[0], stream);
        })
        .then(() => pc.setRemoteDescription({type: 'offer', sdp}))
        .then(() => pc.createAnswer())
        .then((answer) => {
          console.log(answer.sdp);
        });
    });
```

**Comment by fippo** [comment]
The fix from #165 probably opens up a number of additional checks in SRD:
* [ ] check that the mid of an answer matches the offer
* [ ] check the the kind of an answer matches the offer

**Comment by fippo** [comment]
This should be fixed on master -- and unfortunately is too big to backport so will have to wait for the next (major) release.

Please give it a try. And thanks for the report, this was quite some technical debt!

**Comment by syerrapragada** [comment]
Thanks for the Fix. I will give it a try and close the issue

**Comment by syerrapragada** [comment]
Changes look good. But I see a case where setRemoteDescription fails to apply description when in have-local-offer signaling state. I will create a fiddle and share it with you in few hours.

**Comment by syerrapragada** [comment]
Its a test issue where dummy answer SDP we were using didnt match the `mid` in offer. Closing. 

Thank you for the fix.
