### ISSUE TITLE
Is the released version 1.2.14 or 1.2.15?

### ISSUE THREAD

**Issue by itsthetaste** [otalk/rtcpeerconnection-shim#181]
Hi,

Was wondering if this is still the master.  

The npm site and the version of this used within webrtc-adapter refers to 1.2.15.  The repository link npm page (https://www.npmjs.com/package/rtcpeerconnection-shim) says the repository is at;

https://github.com/fippo/rtcpeerconnection-shim

But, clicking the link, brings you here, where the latest release is 1.2.14.

Thanks
Rich

**Comment by fippo** [comment]
looks like I forgot to push (done now). When in doubt, refer to npm

**Comment by itsthetaste** [comment]
nice one.  Thanks :)
