### ISSUE TITLE
Could not complete the operation due to error c004e008

### ISSUE THREAD

**Issue by sherlock1982** [otalk/rtcpeerconnection-shim#96]
Here's an incoming SDP which I feed inside setRemoteDescription. 
This was originally taken from Chrome and slightly modified inside my gateway.

```
v=0
o=WebRTC 328414035 281589450 IN IP4 192.168.1.47
s=3CXWebRTC audio call
c=IN IP4 192.168.1.47
t=0 0
m=audio 9356 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 192.168.1.47
a=rtpmap:111 opus/48000
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ptime:20
a=sendrecv
a=candidate:1234 1 udp 572662306 192.168.1.47 9356 typ host generation 0
a=end-of-candidates
a=ice-ufrag:ISEhISEhISIiISIh
a=ice-pwd:IiIiIiIhIiIiISIhISIhISIi
a=fingerprint:sha-256 12:5C:71:5B:A7:AB:AC:E9:70:22:86:2E:1D:D0:EF:E7:81:47:05:D8:15:B3:A4:D2:DC:11:B1:3A:16:C9:3C:D2
a=rtcp:9356 IN 192.168.1.47
a=rtcp-mux
a=setup:actpass

```
transceiver.rtpReceiver.receive(params) gives me upper error: Could not complete the operation due to error c004e008

It starts to work once I remove opus rtp. 
Do you have any ideas why?

**Comment by fippo** [comment]
https://rawgit.com/aboba/edgertc/master/msortc-rs3.html#error-codes* says this error is unknown codec. Opus mandates a channelcount of 2 and you don't have that here:
> a=rtpmap:111 opus/48000

**Comment by sherlock1982** [comment]
Ok thanks a lot! This is obviously [described here ](https://tools.ietf.org/html/rfc7587) 
Though Chrome and Firefox are tolerant on this.

**Comment by fippo** [comment]
a clear case of https://tools.ietf.org/html/draft-thomson-postel-was-wrong-02 then ;-)
